### ISSUE TITLE
Better method of consistently updating enumerated values needed

### ISSUE THREAD

**Issue by aloafofbrad** [marsilinou97/sunday_supper_donations#10]
So, we've got the enumerated values stored in input/forms.py as lists of 2-tuples. We need a way to update these in one place in case the names change or new values are added (especially for the businesses for gift cards). Maybe we should have these editable on an audit page for admins, and have the forms query the database to see what's in it?

https://github.com/marsilinou97/sunday_supper_donations/blob/a465626d9293a8dcf94bbc24054ecb8c30e5fad6/input/forms.py#L91-L101

https://github.com/marsilinou97/sunday_supper_donations/blob/a465626d9293a8dcf94bbc24054ecb8c30e5fad6/input/forms.py#L134-L139

**Comment by marsilinou97** [comment]
Yes good point, I think we should store them in DB and only query them on the app start to init the lists. When adding/removing an item then update both the list and DB table. We will want to serve the users with the local list and have the DB only as a backup.
