### ISSUE TITLE
Edit page needs table labels

### ISSUE THREAD

**Issue by aloafofbrad** [marsilinou97/sunday_supper_donations#13]
The user will need some way to be able to know what exactly they're editing.

![edit-donation-Screenshot_2021-04-01_16-38-13](https://user-images.githubusercontent.com/30997096/113365272-8ed1c400-930a-11eb-9124-25e9d45ded09.png)

**Comment by marsilinou97** [comment]
Updated dev branch. 
Here's the commit: https://github.com/marsilinou97/sunday_supper_donations/commit/efb8abc7b33c17d5740f61b7605e3536ea8dfc3b 

![image](https://user-images.githubusercontent.com/13006293/114008273-edb9a080-9816-11eb-97f1-06d42ad3b101.png)
