### ISSUE TITLE
Queries needed for managing registration tokens

### ISSUE THREAD

**Issue by aloafofbrad** [marsilinou97/sunday_supper_donations#15]
Queries needed for updating registration tokens
**Query 1.)** This will be used for filling an edit table with registration tokens. We need to see the attributes of each token, and who created it. Get all the attributes from the table users_registrationtoken but only the username from the table auth_user. Should resemble `SELECT urt.id, urt.token, urt.date_created, urt.active, urt.expiration_period, au.username FROM users_registrationtoken urt INNER JOIN auth_user au ON urt.creator_id = au.id;`. 
**Query 2.)** This will be used for updating a selected token's expiration period. Don't update the date created; that should never change. Should resemble `UPDATE users_registrationtoken SET expiration_period = x WHERE id = y;`.

**Query 1.)** Return a list of dictionaries: `[{'urt_id':1,'urt_token':'abc','urt_date_created':'2021-03-17','urt_active':True,'urt_expiration_period':7,'au_username':'John'},...]`. Use default datatypes for the keys 'urt_id', 'urt_active', 'urt_expiration_period', and 'au_id'. The key names don't matter as long as I can tell which table the ids are from.
**Query 2.)** Return a tuple: `(bool,str)`. The bool indicates success. The string contains an error message if there is one.

**Comment by aloafofbrad** [comment]
**Query 2.)** This will now be used for updating a selected token's expiration period and active status. Request input will be a dict `{"expiration_period":x, "active":y, "token":z}`. Should resemble `UPDATE users_registrationtoken SET expiration_period = x, active = y WHERE id = z;`.

**Comment by Rv-ben** [comment]
1. Send `GET` request to `settings/get_token_data`. Might want to see the data before using this.
2. Send `POST` request to `settings/update_token_data`. The request should include a JSON object labeled `update_data`. A full `update_data` will look like this:
`update_data: { active : SOMEDATAHERE, expiration_period: SOMEDATAHERE}`

**Comment by aloafofbrad** [comment]
As far as I can tell these both work properly. They're in use as of this commit https://github.com/marsilinou97/sunday_supper_donations/commit/78b6a5f46730b308d33d14d1976e080dfc84b2fb

Thanks again!
