### ISSUE TITLE
Queries needed for updating users and their roles

### ISSUE THREAD

**Issue by aloafofbrad** [marsilinou97/sunday_supper_donations#17]
**Query 1.)** Get the user's id, username, email address, and the role that they have. The role will be stored in the table `auth_group`. This will be used for filling an edit table with user roles. Be aware that currently, `auth_group` is empty.
**Query 2.)** Should resemble `SELECT * FROM auth_group`. This will be used for selecting an appropriate user role to update a selected user's role.
**Query 3.)** Update a selected user's role. Before you write this you might want to use the django admin page to create a group, add a user to that group, and then examine the database to see where that relationship is stored. I believe it's stored in `auth_user_groups` which is a junction table between `auth_user` and `auth_group`.
**Query 4.)** Should resemble `UPDATE auth_user SET is_active = 'f' WHERE id = x`. This will be used for disabling a selected user. Django recommends this instead of deleting users, to prevent errors with the id sequence. https://docs.djangoproject.com/en/3.1/ref/contrib/auth/#django.contrib.auth.models.User.is_active

**Query 1.)** List of dictionaries. `[{'id':1,'username':'John', 'email':'john123@gmail.com', 'role':'admin'}, ...]`
**Query 2.)** Just a list of strings. `['user','admin','auditor']`. Nothing fancy, nothing extra is needed.
**Query 3.)** Return a tuple: `(bool,str)`. The bool indicates success. The string contains a success/error message. Ideally the data returned from Query 1 will prevent the data in query 2 from being invalid so I think errors should be rare here but they're still possible if multiple users were updating the db.
**Query 4.)** Return a tuple: `(bool,str)`. The bool indicates success. The string contains a success/error message.

**Comment by Rv-ben** [comment]
1. Send `GET` request to this endpoint: `settings/get_user_data`
2. Send `GET` request to this endpoint `settings/get_roles`
3. Send `POST` request to this endpoint `settings/update_user_role`. This request requires two parameters labeled `id` and `role`, which are int and str. 
4. Send `POST` request to this endpoint `settings/activate_user`. This request requires a int parameter labeled `id`.

**Comment by aloafofbrad** [comment]
As far as I can tell these all work properly. They're in use as of this commit https://github.com/marsilinou97/sunday_supper_donations/commit/78b6a5f46730b308d33d14d1976e080dfc84b2fb

Thanks again!
