### ISSUE TITLE
Django query cascades down to other tables

### ISSUE THREAD

**Issue by Rv-ben** [marsilinou97/sunday_supper_donations#6]
### Problem
This query produces 5 others

![image](https://user-images.githubusercontent.com/36426490/110720130-ecb73400-81c2-11eb-9805-d57c9858ff65.png)

The queries it produces:
![image](https://user-images.githubusercontent.com/36426490/110720383-4cadda80-81c3-11eb-82cd-8494c284b24d.png)
![image](https://user-images.githubusercontent.com/36426490/110720404-57686f80-81c3-11eb-916d-2c16e7ff1542.png)
![image](https://user-images.githubusercontent.com/36426490/110720458-6ea75d00-81c3-11eb-966b-1261c032a8f1.png)
![image](https://user-images.githubusercontent.com/36426490/110720433-63ecc800-81c3-11eb-9c2c-6c2dbd93a0c3.png)
![image](https://user-images.githubusercontent.com/36426490/110720467-76ff9800-81c3-11eb-8ebf-165d52748955.png)
![image](https://user-images.githubusercontent.com/36426490/110720489-80890000-81c3-11eb-9bfb-6feb3449411a.png)

**Comment by aloafofbrad** [comment]
Try something like this instead: https://docs.djangoproject.com/en/3.1/topics/db/sql/#passing-parameters-into-raw

**Comment by marsilinou97** [comment]
Can you provide the bug location, please? I can't find any occurrence for that mentioned query. 

Currently, we're handling the raw data page using raw SQL queries that are located under analytics/vars.py instead of Django ORM.

**Comment by Rv-ben** [comment]
It may be the way we built the database:
https://github.com/marsilinou97/sunday_supper_donations/blob/005f9aa733546f699ec81bf2be7f6720e7182388/input/models.py#L14-L239
![image](https://user-images.githubusercontent.com/36426490/112216289-909ad980-8bde-11eb-94d4-e095dd3a6898.png)

**Comment by Rv-ben** [comment]
Fixed:  use django lookup strings in query sets
