### ISSUE TITLE
Chart Queries Needed

### ISSUE THREAD

**Issue by efrn-h** [marsilinou97/sunday_supper_donations#8]
Queries should return a dictionary of the following formats:

**Filters:** first name, last name, donation year

**Query 1,2** have an int list of size 12. Each index holds the donation count for the corresponding month of the year

Used for bar chart #1 
Query 1.) Donations Counts W/ Quantity Included: { "funds" : [22,34,19,14,55,99,23,4,12,5,7,9], ........, "misc" :  [22,34,19,14,55,99,23,4,12,5,7,9] }

Used for bar chart #2 
Query 2.) Donation Count W/O Quantity: { "funds" : [22,34,19,14,55,99,23,4,12,5,7,9],  ......  , "misc" : [22,34,19,14,55,99,23,4,12,5,7,9] }

Used for pie chart
Query 3.) Total Donation Count for Each Category W/ Quantity Included: { "funds" : 25, "giftcards": 35, ..... "misc" : 12 }

Used for donut chart
Query 4.) Total Donation Count for Each Fund Type W/ Quantity Included: {"cash" : 24, "electronic" : 15, "check" : 4}

**Comment by Rv-ben** [comment]
Hit these endpoints for queries: 

1. http://127.0.0.1:8000/analytics/get_donation_count_date_qty/
2. http://127.0.0.1:8000/analytics/get_donation_count_month/
3. http://127.0.0.1:8000/analytics/get_donation_item_count/
4. http://127.0.0.1:8000/analytics/get_donation_fund_count/
