### ISSUE TITLE
Query for input page autofill needed

### ISSUE THREAD

**Issue by aloafofbrad** [marsilinou97/sunday_supper_donations#9]
Query 1 should be something along the lines of "SELECT * FROM input_donor;". I need to be able to iterate over each donor and display their full name, and any non-blank attributes they have. If they have blank attributes that's okay, I think I can work with that. Give me every attribute. It would be ideal if the keys in the dictionaries can match the attribute names from the database exactly. I don't need the anonymous donor, and I don't think it should be included. I plan to use it similarly to how the list of dictionaries is used in this example: https://jqueryui.com/autocomplete/#custom-data

Query 1.) All attributes for all donors currently in the database: `[{'id':2,'first_name':'John', 'last_name':'Jacob', 'email':'abc123@gmail.com', 'phone_number':'', 'address1':'', 'address2':'', 'city:'Anytown', 'state:'ca', 'zip':'12345'}, ... ,{'id':n, 'first_name':'Jingleheimer', 'last_name':'Schmidt', 'phone_number':'', 'address1':'', 'address2':'', 'city':'', state':'', 'zip':''}]`

I don't think I'll need more than one query for this function/page.

**Comment by Rv-ben** [comment]
In the `mz` branch hit  [this link](http://127.0.0.1:8000/input/get_donor_list/)

**Comment by aloafofbrad** [comment]
It's all hooked up. Thanks!
